version: '3'

services:
  # go
  app:
    build:
      context: ./apis/app/api
      dockerfile: ./dockerfile
    env_file:
      - ./apis/app/api/.env
    tty: true
    ports:
      - 80:80
    depends_on:
      - 'app-db'

  # MySQL
  app-db:
    build:
      context: ./apis/app/db
      dockerfile: ./dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./apis/app/db/init.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306